version: '3'

services:

  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    links:
      - postgres:postgres
    env_file:
      - ../.env


  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - "/var/lib/postgresql/data"