"""Add song table

Revision ID: 194a38d5797a
Revises: 039d36099bee
Create Date: 2019-07-01 17:51:30.081499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '194a38d5797a'
down_revision = '039d36099bee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('album', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song')
    # ### end Alembic commands ###
