"""empty message

Revision ID: 6b4811de12ff
Revises: 82ffda53ea82
Create Date: 2019-07-15 13:59:32.797825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b4811de12ff'
down_revision = '82ffda53ea82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('album', 'year')
    # ### end Alembic commands ###
