"""empty message

Revision ID: 82ffda53ea82
Revises: c2f386597245
Create Date: 2019-07-15 12:59:09.345609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82ffda53ea82'
down_revision = 'c2f386597245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('song', sa.Column('album_id', sa.Integer(), nullable=True))
    op.alter_column('song', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('song', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_foreign_key(None, 'song', 'album', ['album_id'], ['id'])
    op.drop_column('song', 'album')
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.add_column('song', sa.Column('album', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'song', type_='foreignkey')
    op.alter_column('song', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('song', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('song', 'album_id')
    op.drop_table('album')
    # ### end Alembic commands ###
