"""empty message

Revision ID: 9193a43c91bd
Revises: 6b4811de12ff
Create Date: 2019-07-15 15:54:16.613195

"""
from alembic import op
import sqlalchemy as sa
import lyrics

# revision identifiers, used by Alembic.
revision = '9193a43c91bd'
down_revision = '6b4811de12ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('uuid', lyrics.database.custom_types.GUID(), nullable=True))
    op.add_column('song', sa.Column('uuid', lyrics.database.custom_types.GUID(), nullable=True))
    op.add_column('user', sa.Column('uuid', lyrics.database.custom_types.GUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'uuid')
    op.drop_column('song', 'uuid')
    op.drop_column('album', 'uuid')
    # ### end Alembic commands ###
