"""empty message

Revision ID: de35353b8292
Revises: 97f232f82a45
Create Date: 2019-07-16 12:40:30.630508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de35353b8292'
down_revision = '97f232f82a45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('album', 'uuid',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
    op.alter_column('song', 'uuid',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
    op.alter_column('user', 'uuid',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'uuid',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    op.alter_column('song', 'uuid',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    op.alter_column('album', 'uuid',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    # ### end Alembic commands ###
